version: '3.7'
services:
  wireshark2chronicle:
    build: .
    network_mode: "host"
    volumes:
      - ./sniff:/app/input
      - ./processed:/app/trash
      - ./chronicle:/app/output
    environment:
      - ROTATE="-b filesize:1024"
      - LIMITS="-c 20000"