version: '3.7'
services:
  wireshark2chronicle:
    build: .
    network_mode: "host"
    volumes:
      - ./input:/app/sniff
      - ./trash:/app/processed
      - ./output:/app/chronicle
    environment:
      - ROTATE="-b filesize:1024"
      - LIMITS="-c 20000"